### ISSUE TITLE
回答済みのアルファベットについて

### ISSUE THREAD

**Issue by c0b21145** [c0b210990e/ProjExD#2]
https://github.com/c0b210990e/ProjExD/blob/c7bc03ad5b565ec1dc73f9cf69966ca9996ca9d4/ex01/alphabet.py#L33

欠損文字をリストなどのコンテナに格納して置いて回答する毎にコンテナから削除すれば回答の重複を解決できると思います。

**Comment by c0b210990e** [comment]
コメントありがとうございます。
