### ISSUE TITLE
反復試行にはfor文

### ISSUE THREAD

**Issue by a123ktx** [c0b210990e/ProjExD#9]
https://github.com/c0b210990e/ProjExD/blob/c5571f798ebb0535fe346159bd8f6e6eb35e548d/ex04/dodge_bomb.py#L34
ここの文、色指定の数値をリストに入れて
for i in List:
 pg.draw...
みたいな感じで書けば見やすくなりそう

**Comment by c0b210990e** [comment]
コメントありがとうございます。
リストにすることはできませんでしたが、今後の参考にさせていただきます。
